# Dockerfile para backend Django
FROM python:3.11-slim

WORKDIR /app

# Copia requirements y los instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

# Expone el puerto donde corre Django
EXPOSE 8000

# Copia y da permisos de ejecución al entrypoint
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Expone el puerto donde corre Django
EXPOSE 8000

# Entrypoint para el contenedor
ENTRYPOINT ["/app/entrypoint.sh"]

# Comando por defecto que se pasa al entrypoint
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

